### ISSUE TITLE
`pess-arb-solidity-version` no longer applies

### ISSUE THREAD

**Issue by 0xalpharush** [pessimistic-io/slitherin#134]
ArbOS 11 added support for PUSH0 and was finalized about two weeks ago

**Comment by 0xEVom** [comment]
Source: https://docs.arbitrum.io/for-devs/concepts/differences-between-arbitrum-ethereum/solidity-support

**Comment by 0xEVom** [comment]
[Source](https://docs.arbitrum.io/for-devs/concepts/differences-between-arbitrum-ethereum/solidity-support)

**Comment by ndkirillov** [comment]
Thanks for pointing out guys. We'll handle this ASAP.
