### ISSUE TITLE
Napalm package / plugin 

### ISSUE THREAD

**Issue by JoranHonig** [pessimistic-io/slitherin#135]
Hey hey,

I recently built a tool that helps people manage their custom detection modules: https://github.com/consensysdiligence/napalm Aside from helping manage modules it also allows for easy distribution and use of different sets of custom modules. 

It would be suuper easy to set up napalm integration for this project! It'd be a couple lines of code that I'd be happy to commit!

With those lines of code people would be able to run slitherin detection modules within their napalm workflows.

Lmk what you think!

---

Here is how people could use this:

https://github.com/ConsenSysDiligence/napalm/blob/main/docs/running-with-napalm.md

**Comment by ndkirillov** [comment]
Hi! Sure, feel free to commit and use our tool in napalm!

**Comment by ndkirillov** [comment]
Released with #157
