### ISSUE TITLE
AttributeError: 'NewContract' object has no attribute '_expression

### ISSUE THREAD

**Issue by julianmrodri** [pessimistic-io/slitherin#151]
Hi, we are facing the following error in our codebase ("AttributeError: 'NewContract' object has no attribute '_expression'") . This is caused by a Slitherin detector because if I run with the `separate` param the Slither parts finishes successfully and the failure is on the Slitherin side.

Any idea what could cause this? Older branches of our codebase finish successfully so its something in our current branches that cannot be parsed correctly I believe. 

Versions:  `slither` 0.10.1, and `slitherin` 0.6.1

The issue is `strange_setter`. I can provide details on how to replicate with our repo which is public. Let me know if that helps..  If I run it with `slitherin . --exclude pess-strange-setter` it finishes successfully.

<img width="1463" alt="image" src="https://github.com/pessimistic-io/slitherin/assets/56316686/265b9a8c-997c-4adc-86cc-50afe8e82f02">

**Comment by olegggatttor** [comment]
I will have a look into it, thanks

**Comment by julianmrodri** [comment]
> I will have a look into it, thanks

Was abole to narrow it to the `strange-setter` detector. All the other seem to work fine. Let me know if you want instructions on how to replicate on our codebase.

**Comment by julianmrodri** [comment]
I can confirm I was able to run all the detectors on my codebase after this change. Its not breaking anymore on `strange-setter`  Do you have en estimate on this change will be published/released?  Thanks a lot!

**Comment by ndkirillov** [comment]
@julianmrodri, released with #157
