### ISSUE TITLE
Feature request: precede detector logs with "slitherin"

### ISSUE THREAD

**Issue by aviggiano** [pessimistic-io/slitherin#81]
Hello,

First of all, thank you for this repo.

I believe it would be nice to precede its logs with "slitherin" so that we know when a finding was reported by it and not by the "original" slither detectors.

For example, when I run it on the `tests/` folder, I get

```
INFO:Detectors:
Contract Bad_UniswapV2_test (tests/Bad_UniswapV2_test.sol#10-99) uses pair contract directly.
```

I suggest it is changed to

```
INFO:Detectors:
slitherin: Contract Bad_UniswapV2_test (tests/Bad_UniswapV2_test.sol#10-99) uses pair contract directly.
```

**Comment by ndkirillov** [comment]
Hi! Thank you for your take! 
We'll see what we can do to enhance the readability of the results. Currently we are also working on writing a script to launch just Slitherin detectors. We'll publish the update soon.

**Comment by ndkirillov** [comment]
Slitherin CLI was added. Check #108
